### ISSUE TITLE
RuntimeError: Triton Error [CUDA]: device kernel image is invalid

### ISSUE THREAD

**Issue by Unrealluver** [sustcsonglin/flash-linear-attention#3]
Greetings!

First off, I want to express my gratitude for sharing your incredible work; it's truly impressive! However, when I attempted to execute the test code outlined in the README, I encountered the following error. Could you kindly offer any guidance or recommendations on how to resolve this issue?

Thank you for your assistance!

```
Traceback (most recent call last):
  File "/share/project/zzzr/jjlm/old_ckpts/VisionProjects/up-to-date-lib/flash-linear-attention/unit_test.py", line 19, in <module>
    y2 = gla(x)
  File "/home/z'z'z/.conda/envs/gla/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/zzz/.conda/envs/gla/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/share/project/zzzr/jjlm/old_ckpts/VisionProjects/up-to-date-lib/flash-linear-attention/fla/layers/gla.py", line 95, in forward
    o = fused_chunk_gla(q, k, v, gk)
  File "/share/project/zzzr/jjlm/old_ckpts/VisionProjects/up-to-date-lib/flash-linear-attention/fla/ops/gla/chunk_fuse.py", line 516, in fused_chunk_gla
    o, final_state = FusedChunkGLAFunction.apply(
  File "/home/zzz/.conda/envs/gla/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/share/project/zzzr/jjlm/old_ckpts/VisionProjects/up-to-date-lib/flash-linear-attention/fla/ops/utils.py", line 11, in wrapper
    return fn(ctx,
  File "/home/zzz/.conda/envs/gla/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/share/project/zzzr/jjlm/old_ckpts/VisionProjects/up-to-date-lib/flash-linear-attention/fla/ops/gla/chunk_fuse.py", line 320, in forward
    fwd_decay_cumsum[grid](
  File "/home/zzz/.conda/envs/gla/lib/python3.10/site-packages/triton/runtime/jit.py", line 550, in run
    bin.c_wrapper(
  File "/home/zzz/.conda/envs/gla/lib/python3.10/site-packages/triton/compiler/compiler.py", line 692, in __getattribute__
    self._init_handles()
  File "/home/zzz/.conda/envs/gla/lib/python3.10/site-packages/triton/compiler/compiler.py", line 683, in _init_handles
    mod, func, n_regs, n_spills = fn_load_binary(self.metadata["name"], self.asm[bin_path], self.shared, device)
RuntimeError: Triton Error [CUDA]: device kernel image is invalid
```

And my environment is shown below:

```
PyTorch version: 2.2.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.26.0
Libc version: glibc-2.31

Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-113-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 470.129.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          256
On-line CPU(s) list:             0-255
Thread(s) per core:              2
Core(s) per socket:              64
Socket(s):                       2
NUMA node(s):                    8
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7742 64-Core Processor
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         3235.858
CPU max MHz:                     2250.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        4491.50
Virtualization:                  AMD-V
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
NUMA node0 CPU(s):               0-15,128-143
NUMA node1 CPU(s):               16-31,144-159
NUMA node2 CPU(s):               32-47,160-175
NUMA node3 CPU(s):               48-63,176-191
NUMA node4 CPU(s):               64-79,192-207
NUMA node5 CPU(s):               80-95,208-223
NUMA node6 CPU(s):               96-111,224-239
NUMA node7 CPU(s):               112-127,240-255
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==2.2.1+cu118
[pip3] torchaudio==2.2.1+cu118
[pip3] torchvision==0.17.1+cu118
[pip3] triton==2.2.0
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] torch                     2.2.1+cu118              pypi_0    pypi
[conda] torchaudio                2.2.1+cu118              pypi_0    pypi
[conda] torchvision               0.17.1+cu118             pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi
```

**Comment by sustcsonglin** [comment]
Hi, can you try to clean the triton cache repo (usually `rm -rf ~/.triton`) first? If not working, please let me know

**Comment by yzhangcs** [comment]
@Unrealluver You can't use Triton>=2.2 with cuda < 12
https://github.com/openai/triton/issues/2855#issuecomment-1889680302

**Comment by 4IK1d** [comment]
> Hi, maybe you can (1) try to clean the triton cache repo (usually `rm -rf ~/.triton`)? (2) update cuda version to >12.0 (it is possibly triton 2.2.0 only support this version), or downgrade triton to 2.1.0 and use `chunk` mode instead of `fused_chunk`. If both not working, please let me know
---
CUDA 11.7 + Triton 2.1.0 + fused_chunk(I'm not sure why fused_chuk work) works for me with GLA.

**Comment by yzhangcs** [comment]
@4IK1d We've provide some [workaround](https://github.com/sustcsonglin/flash-linear-attention/commit/84a3940ab99bccdf1e64e040b78f65d110516365) to support triton 2.1 + `fused_chunk`

**Comment by 4IK1d** [comment]
Ah, that saved my life

**Comment by Unrealluver** [comment]
> Hi, maybe you can (1) try to clean the triton cache repo (usually `rm -rf ~/.triton`)? (2) update cuda version to >12.0 (it is possibly triton 2.2.0 only support this version), or downgrade triton to 2.1.0 and use `chunk` mode instead of `fused_chunk`. If both not working, please let me know

Thanks for this perfect solution! I recommend the setting of torch 2.2 + triton 2.2.0 which works smoothly.
