### ISSUE TITLE
RuntimeError: Triton Error [CUDA]: device-side assert triggered for fla.modules.layernorm.py

### ISSUE THREAD

**Issue by K-H-Ismail** [sustcsonglin/flash-linear-attention#38]
Hello,

I had an issue with the RMS LayerNorm as implemented in the FLA library. It is a ```RuntimeError: Triton Error [CUDA]: device-side assert triggered```. I run on A100 GPUs and on latest versions of torch and triton (I've tried downgrading to minimal requirements). Here is the stacktrace, any idea how to solve this?
```
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/project/main.py", line 372, in <module>
[rank1]:     main()
[rank1]:   File "/home/project/main.py", line 356, in main
[rank1]:     loss = train_batch(opt, model, loss_func, features, labels)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/project/main.py", line 269, in train_batch
[rank1]:     output = model(features, labels=labels)
[rank1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 863, in forward
[rank1]:     output = self._fsdp_wrapped_module(*args, **kwargs)
[rank1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/fla/models/gla/modeling_gla.py", line 367, in forward
[rank1]:     outputs = self.model(
[rank1]:               ^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 863, in forward
[rank1]:     output = self._fsdp_wrapped_module(*args, **kwargs)
[rank1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/fla/models/gla/modeling_gla.py", line 244, in forward
[rank1]:     hidden_states, attentions, past_key_values = layer(
[rank1]:                                                  ^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/fla/models/gla/modeling_gla.py", line 101, in forward
[rank1]:     hidden_states = self.attn_norm(hidden_states)
[rank1]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/fla/modules/layernorm.py", line 657, in forward
[rank1]:     return rms_norm_fn(
[rank1]:            ^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/fla/modules/layernorm.py", line 524, in rms_norm_fn
[rank1]:     return LayerNormFn.apply(
[rank1]:            ^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/torch/autograd/function.py", line 574, in apply
[rank1]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/fla/utils.py", line 11, in wrapper
[rank1]:     return fn(ctx,
[rank1]:            ^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/fla/modules/layernorm.py", line 413, in forward
[rank1]:     y, mean, rstd, residual_out = _layer_norm_fwd(
[rank1]:                                   ^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/fla/modules/layernorm.py", line 169, in _layer_norm_fwd
[rank1]:     _layer_norm_fwd_1pass_kernel[(M,)](
[rank1]:   File "/home/.local/lib/python3.11/site-packages/triton/runtime/jit.py", line 345, in <lambda>
[rank1]:     return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
[rank1]:                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 156, in run
[rank1]:     timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
[rank1]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 156, in <dictcomp>
[rank1]:     timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
[rank1]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 133, in _bench
[rank1]:     return do_bench(kernel_call, warmup=self.num_warmups, rep=self.num_reps, quantiles=(0.5, 0.2, 0.8))
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/triton/testing.py", line 103, in do_bench
[rank1]:     fn()
[rank1]:   File "/home/.local/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 114, in kernel_call
[rank1]:     self.fn.run(
[rank1]:   File "/home/.local/lib/python3.11/site-packages/triton/runtime/jit.py", line 691, in run
[rank1]:     kernel.run(grid_0, grid_1, grid_2, stream, kernel.function, kernel.packed_metadata, launch_metadata,
[rank1]:     ^^^^^^^^^^
[rank1]:   File "/home/.local/lib/python3.11/site-packages/triton/compiler/compiler.py", line 381, in __getattribute__
[rank1]:     self._init_handles()
[rank1]:   File "/home/.local/lib/python3.11/site-packages/triton/compiler/compiler.py", line 376, in _init_handles
[rank1]:     self.module, self.function, self.n_regs, self.n_spills = driver.active.utils.load_binary(
[rank1]:                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: RuntimeError: Triton Error [CUDA]: device-side assert triggered```

**Comment by yzhangcs** [comment]
@K-H-Ismail Hi, could you provide more infos about the versions of PyTorch & Triton and minimal reproducible code.

**Comment by K-H-Ismail** [comment]
Hello @yzhangcs 
torch version 2.4.0
triton version 3.0.0

I'll try to make a minimal code for reproducibility ASAP. I think that this happens when the vocab size in the dataset is larger than the vocab size of the model (32000 here). 

thanks!

**Comment by sustcsonglin** [comment]
@K-H-Ismail  Hi, can you first try Triton=2.2.0? We didn't test FLA on Triton=3.0 yet. (The LayerNorm module is copied from Tri Dao's FlashAttention library and we've actively used it with Triton=2.2.0)

**Comment by K-H-Ismail** [comment]
Hello @sustcsonglin ,

I downgraded to triton==2.2.0 with torch==2.2.0 still the same problem. However when I set the vocab size to the proper dim it works!

Easiest way to reproduce this for you is to take your benchmark for example and change ```high=config.vocab_size``` at line

[        tokens = torch.randint(high=config.vocab_size, size=(batch_size, seq_len)).cuda()](https://github.com/sustcsonglin/flash-linear-attention/blob/bec2845ab3d1f91503b62b4f5249e9934fc3a04a/benchmarks/benchmark_training_throughput.py#L65) 

to something higher like ```high=3*config.vocab_size```

**Comment by K-H-Ismail** [comment]
Thank you for your help, and sorry for the inconvenience, it was all my bad. Maybe we could add an exception or an assert on the vocab size to catch this kind of errors in the future.
