### ISSUE TITLE
[Bug]: Backward pass with AMP not working with GLA and GSA

### ISSUE THREAD

**Issue by Niccolo-Ajroldi** [sustcsonglin/flash-linear-attention#70]
### Describe the bug

When using automatic mixed precision with either `float16`, `bfloat16`, I encounter a casting issue during the **backward** pass:

```plaintext
Traceback (most recent call last):                                                                                                     
  File "/lustre/home/najroldi/flash-linear-attention/train.py", line 29, in <module>                                                   
    loss.backward()                                                                                                                    
  File "/home/najroldi/miniconda3/envs/fla/lib/python3.12/site-packages/torch/_tensor.py", line 521, in backward                       
    torch.autograd.backward(                                                                                                           
  File "/home/najroldi/miniconda3/envs/fla/lib/python3.12/site-packages/torch/autograd/__init__.py", line 289, in backward             
    _engine_run_backward(                                                                                                              
  File "/home/najroldi/miniconda3/envs/fla/lib/python3.12/site-packages/torch/autograd/graph.py", line 769, in _engine_run_backward    
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass                              
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              
  File "/home/najroldi/miniconda3/envs/fla/lib/python3.12/site-packages/torch/autograd/function.py", line 306, in apply                
    return user_fn(self, *args)                                                                                                        
           ^^^^^^^^^^^^^^^^^^^^                                                                                                        
  File "/lustre/home/najroldi/flash-linear-attention/fla/modules/activations.py", line 374, in backward                                
    dz = F.linear(dout, weight.t()).view_as(x)                                                                                         
         ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                    
RuntimeError: expected mat1 and mat2 to have the same dtype, but got: c10::BFloat16 != float 
```

### Steps to reproduce the bug

A minimal example to trigger this issue:

```python
import torch
from torch.nn import CrossEntropyLoss
from fla.models import GLAConfig
from transformers import AutoModelForCausalLM

batch_size, seq_len, vocab_size = 8, 128, 10_000
device, dtype = 'cuda:0', torch.bfloat16

config = GLAConfig(vocab_size=vocab_size, num_hidden_layers=1, hidden_size=256, fuse_cross_entropy=False)
model = AutoModelForCausalLM.from_config(config).to(device)
criterion = CrossEntropyLoss().to(device)

input_ids = torch.randint(0, vocab_size, (batch_size, seq_len)).to(device)
targets = torch.randint(0, vocab_size, (batch_size, seq_len)).to(device)

with torch.amp.autocast(device_type='cuda', dtype=dtype):
    logits = model(input_ids).logits
    loss = criterion(logits.view(-1, logits.size(-1)), targets.reshape(-1))
loss.backward()
```

### Expected behavior

Backward pass runs fine when explicit casting is used (`model = model.to(torch.bfloat16)`), the same should happen when AMP is used. I checked this bug on other models in `fla`, and for now only `GLA` and `GSA` show this behavior.

### Environment info

1. torch: 2.4.1
2. triton: 3.0.0
3. transformers: 4.45.2

GPU: NVIDIA A100-SXM4-80GB

**Comment by yzhangcs** [comment]
@Niccolo-Ajroldi Hi, before autocast, you should cast the model to bfloat16 by `model.bfloat16()` first.

**Comment by Niccolo-Ajroldi** [comment]
@yzhangcs wouldn't that be explicit casting, i.e. cast the model parameters to bfloat16? As far as I know, with autocast we keep them in float32 and compute activations in bf16

Reference: https://discuss.pytorch.org/t/bfloat16-training-explicit-cast-vs-autocast/202618/2?u=coni

**Comment by yzhangcs** [comment]
ah, thank u for the reminder, just fix this bug for autocast.

**Comment by Niccolo-Ajroldi** [comment]
Thank you!
