### ISSUE TITLE
[Bug]: AttributeError: 'tuple' object has no attribute 'backward' in `benchmark_gla.py`

### ISSUE THREAD

**Issue by zml24** [sustcsonglin/flash-linear-attention#80]
### Describe the bug

Traceback (most recent call last):
  File "xxx/flash-linear-attention/benchmarks/ops/benchmark_gla.py", line 81, in <module>
    benchmark.run(print_data=True, save_path='.')
  File "/usr/local/conda/lib/python3.9/site-packages/triton/testing.py", line 341, in run
    result_dfs.append(self._run(bench, save_path, show_plots, print_data, **kwargs))
  File "/usr/local/conda/lib/python3.9/site-packages/triton/testing.py", line 287, in _run
    ret = self.fn(**x_args, **{bench.line_arg: y}, **bench.args, **kwrags)
  File "xxx/flash-linear-attention/benchmarks/ops/benchmark_gla.py", line 74, in benchmark
    results = triton.testing.do_bench(lambda: chunk_gla(q, k, v, g).backward(do), quantiles=quantiles)
  File "/usr/local/conda/lib/python3.9/site-packages/triton/testing.py", line 102, in do_bench
    fn()
  File "xxx/flash-linear-attention/benchmarks/ops/benchmark_gla.py", line 74, in <lambda>
    results = triton.testing.do_bench(lambda: fused_chunk_gla(q, k, v, g).backward(do), quantiles=quantiles)
AttributeError: 'tuple' object has no attribute 'backward'

### Steps to reproduce the bug

Just run `python benchmarks/ops/benchmark_gla.py`

### Expected behavior

Add `[0]` before each `.backward(do)` in this file fix this bug.

### Environment info

1. torch: 2.3.1+cu118
2. triton: 2.3.1

**Comment by yzhangcs** [comment]
Thank you for reporting the issues.
