### ISSUE TITLE
[Bug]:  Triton Compiler Error when Sequence Length <= 8 

### ISSUE THREAD

**Issue by WorldEditors** [sustcsonglin/flash-linear-attention#88]
### Describe the bug

Traceback (most recent call last):
  File "/home/xxx/Codes/tests/test_gsa.py", line 32, in <module>
    y, _, kvs = encoder(inputs[:, b:(b+seg_len)], use_cache=True, past_key_values=kvs)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/fla/layers/gsa.py", line 206, in forward
    o, recurrent_state = chunk_gsa(
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/fla/ops/gsa/chunk.py", line 1241, in chunk_gsa
    o, *final_state = ChunkGSAFunction.apply(
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/fla/utils.py", line 15, in wrapper
    return fn(ctx,
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/fla/ops/gsa/chunk.py", line 1061, in forward
    g_org, g = g, chunk_local_cumsum(g, chunk_size, offsets=offsets, indices=indices, head_first=head_first)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/fla/utils.py", line 15, in wrapper
    return fn(ctx,
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/fla/ops/utils/cumsum.py", line 526, in chunk_local_cumsum
    return chunk_local_cumsum_vector(g, chunk_size, reverse, offsets, indices, head_first)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/fla/ops/utils/cumsum.py", line 497, in chunk_local_cumsum_vector
    chunk_local_cumsum_vector_kernel[grid](
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/triton/runtime/jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 156, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 156, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 133, in _bench
    return do_bench(kernel_call, warmup=self.num_warmups, rep=self.num_reps, quantiles=(0.5, 0.2, 0.8))
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/triton/testing.py", line 103, in do_bench
    fn()
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 114, in kernel_call
    self.fn.run(
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 338, in run
    return self.fn.run(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/triton/runtime/jit.py", line 662, in run
    kernel = self.compile(
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/triton/compiler/compiler.py", line 276, in compile
    module = src.make_ir(options, codegen_fns, context)
  File "/home/xxx/anaconda3/envs/xxx/lib/python3.10/site-packages/triton/compiler/compiler.py", line 113, in make_ir
    return ast_to_ttir(self.fn, self, context=context, options=options, codegen_fns=codegen_fns)
triton.compiler.errors.CompilationError: at 34:10:
    o_i = tl.arange(0, BT)
    m_s = tl.where(o_i[:, None] >= o_i[None, :], 1., 0.)

    if HEAD_FIRST:
        p_s = tl.make_block_ptr(s + i_bh * T*S, (T, S), (S, 1), (i_t * BT, i_s * BS), (BT, BS), (1, 0))
        p_o = tl.make_block_ptr(o + i_bh * T*S, (T, S), (S, 1), (i_t * BT, i_s * BS), (BT, BS), (1, 0))
    else:
        p_s = tl.make_block_ptr(s + (bos * H + i_h) * S, (T, S), (H*S, 1), (i_t * BT, i_s * BS), (BT, BS), (1, 0))
        p_o = tl.make_block_ptr(o + (bos * H + i_h) * S, (T, S), (H*S, 1), (i_t * BT, i_s * BS), (BT, BS), (1, 0))
    # [BT, BS]
    b_s = tl.load(p_s, boundary_check=(0, 1)).to(tl.float32)
    b_o = tl.dot(m_s, b_s, allow_tf32=False)

### Steps to reproduce the bug

```python
import torch
from fla.layers.gsa import GatedSlotAttention
from fla.layers.gla import GatedLinearAttention
from fla.models.utils import Cache

bsz = 4
hidden_size = 256
num_heads = 8
num_slots = 16
seq_len = 100
seg_len = 5  # Will be OK if > 8 

seg_num = (seq_len - 1) // seg_len + 1

encoder = GatedSlotAttention(
          hidden_size=hidden_size,
          num_heads=num_heads,
          num_slots=num_slots,
          layer_idx=0)

encoder = encoder.to('cuda')
inputs = torch.randn(bsz, seq_len, hidden_size, device='cuda')
outputs = torch.randn(bsz, seq_len, hidden_size, device='cuda')

encoder.eval()
kvs = Cache.from_legacy_cache(None)

b = 0
loss_step = 0
with torch.no_grad():
    for seg_id in range(seg_num):
        y, _, kvs = encoder(inputs[:, b:(b+seg_len)], use_cache=True, past_key_values=kvs)
        loss_step += torch.sum((y - outputs[:, b:(b+seg_len)]) ** 2)

        kvs_sum = Cache.from_legacy_cache(None)
        ysum, _, new_cache_sum = encoder(inputs[:, :(b+seg_len)], use_cache=True, past_key_values=kvs_sum)
        loss_sum = torch.sum((ysum - outputs[:, :(b+seg_len)]) ** 2)

        print(b, "loss diff", loss_sum - loss_step)    # keeping getting larger from 0 as the step continues
        for c1, c2 in zip(kvs.states[0]["recurrent_state"], new_cache_sum.states[0]["recurrent_state"]):
            print(b, "cache diff:", torch.sum((c1 - c2)**2))

        b += seg_len
```

### Expected behavior

N/A

### Environment info

1. torch:  2.4.1
2. triton:  3.0.0

**Comment by WorldEditors** [comment]
Switch TO mode = "fused_recurrent" FIXED this problem
seems only appear in "chunk" mode

**Comment by zml24** [comment]
when using `chunk` mode, the code use triton to recurrently compute sequence block output. And the minimal value of triton acceptable block dim is 16.

**Comment by yzhangcs** [comment]
@WorldEditors 
Thank you for reporting this. I will be looking at this.
And yeeesss! It's highly recommended to using `fused_recurrent` for seqlens < 64 as we do not thoroughly check the correctness for very short sequences. The `chunk` mode is inefficient for them due to excessive padding.

**Comment by yzhangcs** [comment]
Fixed by https://github.com/sustcsonglin/flash-linear-attention/commit/01f02517b80a1c8f2d3d7d39b5a7cac16b705003
