### ISSUE TITLE
[Bug]: Triton Error with `GatedDeltaNet` in Triton 2.2.0 and 2.3.x

### ISSUE THREAD

**Issue by xffxff** [sustcsonglin/flash-linear-attention#97]
### Describe the bug

I encountered an error when trying to run the `GatedDeltaNet` model with Triton 2.2.0 and versions 2.3 and 2.3.1. The error message states: "error: operand 1 does not dominate this use". However, the code works fine with Triton version 3.0.

<details>

<summary>The full error log</summary>

```text
loc(fused["/root/miniconda3/lib/python3.10/site-packages/fla/ops/gated_delta_rule/wy_fast.py":160:16, "/root/miniconda3/lib/python3.10/site-packages/fla/ops/gated_delta_rule/wy_fast.py":160:29]): error: operand #1 does not dominate this use
Traceback (most recent call last):
  File "/gpfs/public/pretrain/zhoufan/moba/moba/gated_delta_net.py", line 17, in <module>
    print(model(input_ids))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/fla/models/gated_deltanet/modeling_gated_deltanet.py", line 398, in forward
    outputs = self.model(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/fla/models/gated_deltanet/modeling_gated_deltanet.py", line 270, in forward
    hidden_states, attentions, past_key_values = layer(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/fla/models/gated_deltanet/modeling_gated_deltanet.py", line 131, in forward
    hidden_states, attentions, past_key_values = self.attn(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/fla/layers/gated_deltanet.py", line 246, in forward
    o, recurrent_state = chunk_gated_delta_rule(
  File "/root/miniconda3/lib/python3.10/site-packages/fla/ops/gated_delta_rule/chunk.py", line 1195, in chunk_gated_delta_rule
    o, final_state = ChunkDeltaRuleFunction.apply(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/lib/python3.10/site-packages/fla/utils.py", line 18, in wrapper
    return fn(ctx,
  File "/root/miniconda3/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 455, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/fla/ops/gated_delta_rule/chunk.py", line 1051, in forward
    g, o, Aw, Au, final_state = chunk_gated_delta_rule_fwd(
  File "/root/miniconda3/lib/python3.10/site-packages/fla/ops/gated_delta_rule/chunk.py", line 880, in chunk_gated_delta_rule_fwd
    w, u, Aw, Au = fwd_prepare_wy_repr(
  File "/root/miniconda3/lib/python3.10/site-packages/fla/ops/gated_delta_rule/wy_fast.py", line 343, in fwd_prepare_wy_repr
    fwd_fn[(NT, B*H)](
  File "/root/miniconda3/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 305, in run
    return self.fn.run(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 143, in run
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/root/miniconda3/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 143, in <dictcomp>
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
  File "/root/miniconda3/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 122, in _bench
    return do_bench(kernel_call, warmup=self.warmup, rep=self.rep, quantiles=(0.5, 0.2, 0.8))
  File "/root/miniconda3/lib/python3.10/site-packages/triton/testing.py", line 102, in do_bench
    fn()
  File "/root/miniconda3/lib/python3.10/site-packages/triton/runtime/autotuner.py", line 110, in kernel_call
    self.fn.run(
  File "/root/miniconda3/lib/python3.10/site-packages/triton/runtime/jit.py", line 532, in run
    self.cache[device][key] = compile(
  File "/root/miniconda3/lib/python3.10/site-packages/triton/compiler/compiler.py", line 543, in compile
    next_module = compile_kernel(module)
  File "/root/miniconda3/lib/python3.10/site-packages/triton/compiler/compiler.py", line 437, in <lambda>
    stages["ttgir"] = (lambda path: parse_mlir_module(path, context), lambda src: optimize_ttgir(
  File "/root/miniconda3/lib/python3.10/site-packages/triton/compiler/compiler.py", line 151, in optimize_ttgir
    pm.run(mod)
RuntimeError: PassManager::run failed
```
</details>

### Steps to reproduce the bug

```python
from fla.layers.gated_deltanet import GatedDeltaNet
import torch


hidden_size = 1000
seq_len = 128
layer = GatedDeltaNet(hidden_size=hidden_size).to(torch.bfloat16).to("cuda")

x = torch.randn(1, seq_len, hidden_size).to(torch.bfloat16).to("cuda")

layer(x)
```

### Expected behavior

The model should run without errors.

### Environment info

1. torch: 2.4.0
2. triton: 2.2.0

**Comment by sustcsonglin** [comment]
hi, is there a specific reason to use Triton 2.2 or 2.3?  Or we would focus on supporting Triton 3.0 instead.

**Comment by xffxff** [comment]
> hi, is there a specific reason to use Triton 2.2 or 2.3? Or we would focus on supporting Triton 3.0 instead.

We can focus on supporting Triton 3.0. I noticed that you previously mentioned Triton 2.2 as being reliable for chunk parallelism in the README. However, I see that this section has been removed, and the README now requires Triton 3.0 instead.

**Comment by sustcsonglin** [comment]
> removed

Thank you. We just updated the README due to this issue. Triton 3.0 is now stable and  the default version when calling `pip install triton`. We don't have plans to ensure the compatibilities for Triton 2, instead, we encourage users to use Triton 3.
