### ISSUE TITLE
[Bug]: Shape mismatch, can't divide axis of length 1334 in chunks of 83

### ISSUE THREAD

**Issue by zmj1203** [sustcsonglin/flash-linear-attention#98]
### Describe the bug

Hi~

New bugs during evaluating GLA-340M-15B model in fused chunk setup:

### Steps to reproduce the bug

1. Download GLA-340M-15B model from https://hf-mirror.com/fla-hub/gla-340M-15B
2. Download and install fla from https://github.com/sustcsonglin/flash-linear-attention and https://github.com/EleutherAI/lm-evaluation-harness
3. Run the command:
CUDA_VISIBLE_DEVICES=x python -u -m evals.harness --model hf --model_args pretrained="xxx/gla-340M-15B" --tasks lambada_openai,arc_easy,arc_challenge,winogrande,openbookqa,sciq,copa,wikitext,boolq --batch_size 64 --num_fewshot 0 --device cuda:0 --show_config 

### Expected behavior

Running loglikelihood requests:   0%|          | 0/34615 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/einops/einops.py", line 523, in reduce
    return _apply_recipe(
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/einops/einops.py", line 234, in _apply_recipe
    init_shapes, axes_reordering, reduced_axes, added_axes, final_shapes, n_axes_w_added = _reconstruct_from_shape(
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/einops/einops.py", line 187, in _reconstruct_from_shape_uncached
    raise EinopsError(f"Shape mismatch, can't divide axis of length {length} in chunks of {known_product}")
einops.EinopsError: Shape mismatch, can't divide axis of length 1334 in chunks of 83

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/xxx/flash-linear-attention-main-20241223/evals/harness.py", line 21, in <module>
    cli_evaluate()
  File "/xxx/lm-evaluation-harness-main/lm_eval/__main__.py", line 382, in cli_evaluate
    results = evaluator.simple_evaluate(
  File "/xxx/lm-evaluation-harness-main/lm_eval/utils.py", line 397, in _wrapper
    return fn(*args, **kwargs)
  File "/xxx/lm-evaluation-harness-main/lm_eval/evaluator.py", line 303, in simple_evaluate
    results = evaluate(
  File "/xxx/lm-evaluation-harness-main/lm_eval/utils.py", line 397, in _wrapper
    return fn(*args, **kwargs)
  File "/xxx/lm-evaluation-harness-main/lm_eval/evaluator.py", line 507, in evaluate
    resps = getattr(lm, reqtype)(cloned_reqs)
  File "/xxx/lm-evaluation-harness-main/lm_eval/api/model.py", line 378, in loglikelihood
    return self._loglikelihood_tokens(new_reqs, disable_tqdm=disable_tqdm)
  File "/xxx/lm-evaluation-harness-main/lm_eval/models/huggingface.py", line 1143, in _loglikelihood_tokens
    self._model_call(batched_inps, **call_kwargs), dim=-1
  File "/xxx/lm-evaluation-harness-main/lm_eval/models/huggingface.py", line 856, in _model_call
    return self.model(inps).logits
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)                                                                                                                    File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl                return forward_call(*args, **kwargs)                                                                                                                       File "/xxx/flash-linear-attention-main-20241223/fla/models/gla/modeling_gla.py", line 383, in forward
 outputs = self.model(
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/xxx/flash-linear-attention-main-20241223/fla/models/gla/modeling_gla.py", line 255, in forward
    hidden_states, attentions, past_key_values = layer(
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/xxx/flash-linear-attention-main-20241223/fla/models/gla/modeling_gla.py", line 120, in forward
    hidden_states, attentions, past_key_values = self.attn(
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/xxx/flash-linear-attention-main-20241223/fla/layers/gla.py", line 233, in forward
    o, recurrent_state = fused_chunk_gla(
  File "/xxx/flash-linear-attention-main-20241223/fla/ops/gla/fused_chunk.py", line 640, in fused_chunk_gla
    o, final_state = FusedChunkGLAFunction.apply(q, k, v, g, scale, initial_state, output_final_state)
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/xxx/flash-linear-attention-main-20241223/fla/utils.py", line 15, in wrapper
    return fn(ctx,
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 115, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/xxx/flash-linear-attention-main-20241223/fla/ops/gla/fused_chunk.py", line 467, in forward
    v2 = rearrange(v, 'b h (n c) d -> b h n c d', n=num_chunk)
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/einops/einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
  File "/home/xxx/miniconda3/envs/py310_cu118_torch22/lib/python3.10/site-packages/einops/einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "b h (n c) d -> b h n c d".
 Input tensor shape: torch.Size([64, 16, 1334, 256]). Additional info: {'n': 83}.
 Shape mismatch, can't divide axis of length 1334 in chunks of 83
Running loglikelihood requests:   0%|          | 0/34615 [00:08<?, ?it/s]

### Environment info

python 3.10.0
absl-py 2.1.0
accelerate 1.1.1
aiohappyeyeballs 2.4.4
aiohttp 3.11.9
aiosignal 1.3.1
annotated-types 0.7.0
async-timeout 5.0.1
attrs 24.2.0
causal-conv1d 1.5.0.post8
certifi 2022.12.7
chardet 5.2.0
charset-normalizer 2.1.1
click 8.1.7
colorama 0.4.6
DataProperty 1.0.1
datasets 2.16.0
deepspeed 0.16.0
dill 0.3.7
docker-pycreds 0.4.0
einops 0.8.0
evaluate 0.4.3
filelock 3.13.1
fla 0.1
flash-attn 2.7.2.post1
flash-rwkv 0.3.0
frozenlist 1.5.0
fsspec 2023.10.0
gitdb 4.0.11
GitPython 3.1.43
hjson 3.1.0
huggingface-hub 0.27.0
idna 3.4
Jinja2 3.1.3
joblib 1.4.2
jsonlines 4.0.0
lightning-utilities 0.11.9
lm_eval 0.4.5
lxml 5.3.0
mamba-ssm 2.2.4
MarkupSafe 2.1.5
mbstrdecoder 1.1.3
more-itertools 10.5.0
mpmath 1.3.0
msgpack 1.1.0
multidict 6.1.0
multiprocess 0.70.15
networkx 3.2.1
ninja 1.11.1.2
nltk 3.9.1
numexpr 2.10.2
numpy 1.26.3
nvidia-cublas-cu11 11.11.3.6
nvidia-cuda-cupti-cu11 11.8.87
nvidia-cuda-nvrtc-cu11 11.8.89
nvidia-cuda-runtime-cu11 11.8.89
nvidia-cudnn-cu11 8.7.0.84
nvidia-cufft-cu11 10.9.0.58
nvidia-curand-cu11 10.3.0.86
nvidia-cusolver-cu11 11.4.1.48
nvidia-cusparse-cu11 11.7.5.86
nvidia-ml-py 12.560.30
nvidia-nccl-cu11 2.19.3
nvidia-nvtx-cu11 11.8.86
packaging 24.2
pandas 2.2.3
pathvalidate 3.2.1
peft 0.13.2
pillow 10.2.0
pip 24.2
platformdirs 4.3.6
portalocker 3.0.0
propcache 0.2.1
protobuf 5.29.1
psutil 6.1.0
py-cpuinfo 9.0.0
pyarrow 18.1.0
pyarrow-hotfix 0.6
pybind11 2.13.6
pydantic 2.10.3
pydantic_core 2.27.1
pytablewriter 1.2.0
python-dateutil 2.9.0.post0
pytorch-lightning 2.4.0
pytz 2024.2
PyYAML 6.0.2
regex 2024.11.6
requests 2.32.3
rouge_score 0.1.2
rwkv 0.8.28
sacrebleu 2.4.3
safetensors 0.4.5
scikit-learn 1.5.2
scipy 1.14.1
sentencepiece 0.2.0
sentry-sdk 2.19.0
setproctitle 1.3.4
setuptools 75.1.0
six 1.17.0
smmap 5.0.1
sqlitedict 2.1.0
sympy 1.13.1
tabledata 1.3.3
tabulate 0.9.0
tcolorpy 0.1.6
threadpoolctl 3.5.0
tokenizers 0.21.0
torch 2.2.0+cu118
torchaudio 2.2.0+cu118
torchmetrics 1.6.0
torchvision 0.17.0+cu118
tqdm 4.67.1
tqdm-multiprocess 0.0.11
transformers 4.47.1
triton 2.2.0
typepy 1.3.2
typing_extensions 4.12.2
tzdata 2024.2
urllib3 1.26.13
wheel 0.44.0
word2number 1.1
xxhash 3.5.0
yarl 1.18.3
zstandard 0.23.0

I also try the cu121/cu124+torch2.4.0, it do not work

**Comment by yzhangcs** [comment]
@zmj1203 Hi, can you check it again. Already switch the default attn mode to `chunk`.
I will fix problems regarding `fused_chunk` soon.

**Comment by yzhangcs** [comment]
Fixed by https://github.com/sustcsonglin/flash-linear-attention/commit/1e04390b3d5522da7a5574987527f02b0e048154

**Comment by zmj1203** [comment]
> @zmj1203 Hi, can you check it again. Already switch the default attn mode to `chunk`. I will fix problems regarding `fused_chunk` soon.




> @zmj1203 Hi, can you check it again. Already switch the default attn mode to `chunk`. I will fix problems regarding `fused_chunk` soon.

Hi~

I know that I can run the code successfully if I set to 'chunk'.
But if it use the default setup 'fused_chunk', it failed. So it is a bug that need to be fixed.

**Comment by yzhangcs** [comment]
yes, sry that it's a bug introduced by recent seq-first commits.
I've added an workaround for it. You can try it now.
Please be careful that we've conducted some padding to deal with lengths not power of 2 in `fused_chunk`. 
So for optimal performance, it's highly recommended to use `chunk`.
